from __future__ import annotations

import concurrent.futures
import ipaddress
import json
import os
import re
import subprocess
import tempfile
from collections import defaultdict
from pathlib import Path
from urllib.parse import unquote, urlparse

import requests
import yaml
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry


# ============================================================
# Basic configuration
# ============================================================

REPO_ROOT = Path(__file__).resolve().parent
LINKS_FILE = REPO_ROOT / "links.txt"
OUTPUT_DIR = REPO_ROOT / "rule"

# Keep version 2 for compatibility.
# sing-box 1.13.x can compile version 2 rule-set source files.
RULE_SET_VERSION = 2

CONNECT_TIMEOUT = 10
READ_TIMEOUT = 30
MAX_WORKERS = 8


# ============================================================
# Rule type mapping
# ============================================================

TYPE_MAP = {
    "DOMAIN-SUFFIX": "domain_suffix",
    "HOST-SUFFIX": "domain_suffix",

    "DOMAIN": "domain",
    "HOST": "domain",

    "DOMAIN-KEYWORD": "domain_keyword",
    "HOST-KEYWORD": "domain_keyword",

    "IP-CIDR": "ip_cidr",
    "IP-CIDR6": "ip_cidr",
    "IP6-CIDR": "ip_cidr",

    "SRC-IP-CIDR": "source_ip_cidr",

    "DST-PORT": "port",
    "SRC-PORT": "source_port",

    "URL-REGEX": "domain_regex",
    "DOMAIN-REGEX": "domain_regex",
}


FIELD_ORDER = (
    "domain",
    "domain_suffix",
    "domain_keyword",
    "domain_regex",

    "ip_cidr",
    "source_ip_cidr",

    "port",
    "port_range",

    "source_port",
    "source_port_range",
)


# These rule types cannot be directly converted to the simple
# sing-box headless rule-set structure generated by this script.
UNSUPPORTED_TYPES = {
    "AND",
    "OR",
    "NOT",

    "GEOIP",
    "GEOSITE",

    "RULE-SET",

    "MATCH",
    "FINAL",

    "PROCESS-NAME",
    "PROCESS-PATH",

    "USER-AGENT",

    "NETWORK",
}


# ============================================================
# HTTP
# ============================================================

def make_session():
    retry = Retry(
        total=3,
        connect=3,
        read=3,
        status=3,

        backoff_factor=1,

        status_forcelist=(
            429,
            500,
            502,
            503,
            504,
        ),

        allowed_methods=frozenset({
            "GET",
        }),

        raise_on_status=False,
    )

    adapter = HTTPAdapter(
        max_retries=retry,
    )

    session = requests.Session()

    session.headers.update({
        "User-Agent": "Mozilla/5.0",
    })

    session.mount(
        "http://",
        adapter,
    )

    session.mount(
        "https://",
        adapter,
    )

    return session


def fetch_text(url):
    with make_session() as session:
        response = session.get(
            url,

            timeout=(
                CONNECT_TIMEOUT,
                READ_TIMEOUT,
            ),
        )

        response.raise_for_status()

        return response.text


# ============================================================
# links.txt
# ============================================================

def read_links():
    if not LINKS_FILE.is_file():
        raise FileNotFoundError(
            f"Missing links.txt: {LINKS_FILE}"
        )

    links = [
        line.strip()

        for line in LINKS_FILE
        .read_text(
            encoding="utf-8"
        )
        .splitlines()

        if line.strip()
        and not line.lstrip().startswith("#")
    ]

    if not links:
        raise RuntimeError(
            "links.txt contains no active URLs."
        )

    return links


# ============================================================
# Output filename
# ============================================================

def output_name(url):
    filename = Path(
        unquote(
            urlparse(url).path
        )
    ).name

    if not filename:
        raise ValueError(
            f"Cannot derive filename from URL: {url}"
        )

    name = Path(filename).stem

    name = re.sub(
        r"[^A-Za-z0-9._-]+",
        "_",
        name,
    ).strip("._-")

    if not name:
        raise ValueError(
            f"Invalid output filename for URL: {url}"
        )

    return name


# ============================================================
# Source extraction
# ============================================================

def extract_items(text):
    """
    Supported source examples:

    Clash YAML:

        payload:
          - '+.example.com'
          - 'DOMAIN,example.org'
          - 'IP-CIDR,1.2.3.0/24'

    YAML list:

        - DOMAIN,example.com
        - DOMAIN-SUFFIX,example.org

    Plain text:

        DOMAIN,example.com
        IP-CIDR,1.2.3.0/24
    """

    try:
        data = yaml.safe_load(text)

    except yaml.YAMLError:
        data = None


    # Clash-style YAML:
    #
    # payload:
    #   - rule
    #   - rule
    #
    if (
        isinstance(data, dict)
        and isinstance(
            data.get("payload"),
            list,
        )
    ):

        return [
            str(item).strip()

            for item in data["payload"]

            if item is not None
            and str(item).strip()
        ]


    # Direct YAML list
    if isinstance(data, list):

        return [
            str(item).strip()

            for item in data

            if item is not None
            and str(item).strip()
        ]


    # Plain text fallback
    items = []

    for raw in text.splitlines():

        line = raw.strip()

        if not line:
            continue

        if line.startswith((
            "#",
            ";",
            "//",
        )):
            continue


        # Basic YAML-list-like text support
        if line.startswith("- "):

            line = line[2:].strip()


        # Remove inline comments only when "#" is preceded
        # by whitespace.
        line = re.sub(
            r"\s+#.*$",
            "",
            line,
        ).strip()


        line = line.strip(
            "'\""
        )


        if line:
            items.append(line)


    return items


# ============================================================
# IP processing
# ============================================================

def looks_like_ip(value):

    try:

        if "/" in value:

            ipaddress.ip_network(
                value,
                strict=False,
            )

        else:

            ipaddress.ip_address(
                value
            )

        return True


    except ValueError:

        return False


def normalize_ip(value):

    value = value.strip()


    try:

        # CIDR
        if "/" in value:

            return ipaddress.ip_network(
                value,
                strict=False,
            ).with_prefixlen


        # Single IP
        return ipaddress.ip_address(
            value
        ).compressed


    except ValueError as exc:

        raise ValueError(
            f"Invalid IP/CIDR: {value}"
        ) from exc


# ============================================================
# Domain processing
# ============================================================

def normalize_suffix(value):

    value = value.strip()


    # Clash:
    #
    # +.example.com
    #
    if value.startswith("+."):

        value = value[2:]


    elif value.startswith("."):

        value = value[1:]


    if not value:

        raise ValueError(
            "Empty domain suffix."
        )


    return value


# ============================================================
# Port processing
# ============================================================

def normalize_port(
    value,
    field,
):

    value = value.strip()


    # Examples:
    #
    # 1000-2000
    # 1000:2000
    # :2000
    # 1000:
    #
    match = re.fullmatch(
        r"(\d*)\s*[-:]\s*(\d*)",
        value,
    )


    if match:

        start_text, end_text = (
            match.groups()
        )


        if (
            not start_text
            and not end_text
        ):

            raise ValueError(
                f"Invalid port range: {value}"
            )


        start = (
            int(start_text)
            if start_text
            else None
        )


        end = (
            int(end_text)
            if end_text
            else None
        )


        for port in (
            start,
            end,
        ):

            if (
                port is not None
                and not 0 <= port <= 65535
            ):

                raise ValueError(
                    f"Port out of range: {value}"
                )


        if (
            start is not None
            and end is not None
            and start > end
        ):

            raise ValueError(
                f"Invalid port range: {value}"
            )


        range_field = (
            "port_range"

            if field == "port"

            else "source_port_range"
        )


        normalized = (
            f"{'' if start is None else start}:"
            f"{'' if end is None else end}"
        )


        return (
            range_field,
            normalized,
        )


    # Single port
    port = int(value)


    if not 0 <= port <= 65535:

        raise ValueError(
            f"Port out of range: {value}"
        )


    return (
        field,
        port,
    )


# ============================================================
# Single rule parser
# ============================================================

def parse_item(item):

    item = item.strip()


    # --------------------------------------------------------
    # Bare domain suffix
    #
    # +.example.com
    # .example.com
    # --------------------------------------------------------

    if (
        item.startswith("+.")
        or item.startswith(".")
    ):

        return (
            "domain_suffix",
            normalize_suffix(item),
        )


    # --------------------------------------------------------
    # Bare IP / CIDR / domain
    # --------------------------------------------------------

    if "," not in item:

        if looks_like_ip(item):

            return (
                "ip_cidr",
                normalize_ip(item),
            )


        return (
            "domain",
            item,
        )


    # --------------------------------------------------------
    # Typed rule
    # --------------------------------------------------------

    rule_type, remainder = (
        item.split(
            ",",
            1,
        )
    )


    rule_type = (
        rule_type
        .strip()
        .upper()
    )


    remainder = (
        remainder.strip()
    )


    # Known unsupported type
    if rule_type in UNSUPPORTED_TYPES:

        return None


    field = TYPE_MAP.get(
        rule_type
    )


    # Unknown type:
    #
    # ignore it instead of creating invalid sing-box JSON.
    if field is None:

        return None


    # Regex may contain commas.
    if field == "domain_regex":

        value = remainder


    else:

        # Remove optional fields such as:
        #
        # IP-CIDR,1.2.3.0/24,no-resolve
        #
        value = remainder.split(
            ",",
            1,
        )[0].strip()


    if not value:

        raise ValueError(
            f"Missing value: {item}"
        )


    # --------------------------------------------------------
    # Domain suffix
    # --------------------------------------------------------

    if field == "domain_suffix":

        return (
            field,
            normalize_suffix(value),
        )


    # --------------------------------------------------------
    # Domain
    # --------------------------------------------------------

    if field in {
        "domain",
        "domain_keyword",
        "domain_regex",
    }:

        return (
            field,
            value,
        )


    # --------------------------------------------------------
    # IP
    # --------------------------------------------------------

    if field in {
        "ip_cidr",
        "source_ip_cidr",
    }:

        return (
            field,
            normalize_ip(value),
        )


    # --------------------------------------------------------
    # Port
    # --------------------------------------------------------

    if field in {
        "port",
        "source_port",
    }:

        return normalize_port(
            value,
            field,
        )


    raise ValueError(
        f"Unhandled field: {field}"
    )


# ============================================================
# Parse one remote source
# ============================================================

def parse_source(url):

    name = output_name(url)


    print(
        f"[FETCH] {name}: {url}",
        flush=True,
    )


    text = fetch_text(url)


    items = extract_items(text)


    if not items:

        raise RuntimeError(
            f"{name}: no rules found."
        )


    fields = defaultdict(set)

    skipped = 0


    for index, item in enumerate(
        items,
        start=1,
    ):

        try:

            parsed = parse_item(item)


        except Exception as exc:

            raise ValueError(
                f"{name}: failed at item "
                f"#{index}: "
                f"{item!r}: "
                f"{exc}"
            ) from exc


        if parsed is None:

            skipped += 1

            continue


        field, value = parsed


        fields[field].add(
            value
        )


    if not fields:

        raise RuntimeError(
            f"{name}: all "
            f"{len(items)} rules "
            f"were unsupported."
        )


    # --------------------------------------------------------
    # Deterministic sorting
    # --------------------------------------------------------

    normalized = {}


    for field in FIELD_ORDER:

        if field not in fields:

            continue


        # Numeric port sorting
        if field in {
            "port",
            "source_port",
        }:

            normalized[field] = sorted(
                fields[field]
            )


        else:

            normalized[field] = sorted(
                fields[field],

                key=lambda value:
                    str(value).casefold(),
            )


    kept = sum(
        len(values)

        for values
        in normalized.values()
    )


    print(
        f"[OK] {name}: "
        f"{kept} unique rules, "
        f"{skipped} unsupported rules skipped",
        flush=True,
    )


    return (
        name,
        normalized,
    )


# ============================================================
# Write JSON and compile SRS
# ============================================================

def write_and_compile(
    name,
    fields,
    staging_dir,
):

    json_path = (
        staging_dir
        / f"{name}.json"
    )


    srs_path = (
        staging_dir
        / f"{name}.srs"
    )


    payload = {

        "version": RULE_SET_VERSION,

        "rules": [

            {
                field: fields[field]
            }

            for field
            in FIELD_ORDER

            if field in fields
        ],
    }


    # --------------------------------------------------------
    # Write JSON
    # --------------------------------------------------------

    with json_path.open(
        "w",
        encoding="utf-8",
        newline="\n",
    ) as file:

        json.dump(
            payload,
            file,
            ensure_ascii=False,
            indent=2,
        )

        file.write("\n")


    # --------------------------------------------------------
    # Compile SRS
    # --------------------------------------------------------

    print(
        f"[COMPILE] {name}",
        flush=True,
    )


    subprocess.run(
        [
            "sing-box",
            "rule-set",
            "compile",

            "--output",
            str(srs_path),

            str(json_path),
        ],

        check=True,
    )


    # --------------------------------------------------------
    # Verify output
    # --------------------------------------------------------

    if (
        not srs_path.is_file()
        or srs_path.stat().st_size == 0
    ):

        raise RuntimeError(
            f"{name}: "
            f"SRS output is missing or empty."
        )


# ============================================================
# Publish
# ============================================================

def publish(
    staging_dir,
    names,
):

    expected = {

        f"{name}{extension}"

        for name
        in names

        for extension
        in (
            ".json",
            ".srs",
        )
    }


    # --------------------------------------------------------
    # Remove obsolete generated files
    #
    # This happens ONLY after all downloads and compilation
    # operations have succeeded.
    # --------------------------------------------------------

    for pattern in (
        "*.json",
        "*.srs",
    ):

        for old_file in OUTPUT_DIR.glob(
            pattern
        ):

            if old_file.name not in expected:

                print(
                    f"[REMOVE] "
                    f"{old_file.name}",
                    flush=True,
                )

                old_file.unlink()


    # --------------------------------------------------------
    # Replace current outputs
    # --------------------------------------------------------

    for filename in sorted(expected):

        source = (
            staging_dir
            / filename
        )


        if not source.is_file():

            raise RuntimeError(
                f"Missing staged output: "
                f"{source}"
            )


        destination = (
            OUTPUT_DIR
            / filename
        )


        os.replace(
            source,
            destination,
        )


        print(
            f"[WRITE] "
            f"{destination.relative_to(REPO_ROOT)}",
            flush=True,
        )


# ============================================================
# Main
# ============================================================

def main():

    links = read_links()


    names = [
        output_name(url)

        for url
        in links
    ]


    # --------------------------------------------------------
    # Prevent two URLs from overwriting the same output name
    # --------------------------------------------------------

    duplicates = sorted({

        name

        for name
        in names

        if names.count(name) > 1

    })


    if duplicates:

        raise RuntimeError(
            "Duplicate output names: "
            + ", ".join(duplicates)
        )


    print(
        f"Loaded "
        f"{len(links)} "
        f"rule source(s).",
        flush=True,
    )


    results = {}

    failures = []


    # ========================================================
    # Parallel download + parse
    # ========================================================

    with concurrent.futures.ThreadPoolExecutor(

        max_workers=min(
            MAX_WORKERS,
            len(links),
        )

    ) as executor:


        futures = {

            executor.submit(
                parse_source,
                url,
            ): url

            for url
            in links
        }


        for future in concurrent.futures.as_completed(
            futures
        ):

            url = futures[future]


            try:

                name, fields = (
                    future.result()
                )


                results[url] = (
                    name,
                    fields,
                )


            except Exception as exc:

                failures.append(
                    (
                        url,
                        exc,
                    )
                )


                print(
                    f"[ERROR] "
                    f"{url}: "
                    f"{exc}",
                    flush=True,
                )


    # ========================================================
    # Do NOT touch existing rules when any source failed
    # ========================================================

    if failures:

        details = "\n".join(

            f"  - {url}: {error}"

            for url, error
            in failures
        )


        raise RuntimeError(
            f"{len(failures)} "
            f"source(s) failed. "
            f"Existing rule files "
            f"were not changed:\n"
            f"{details}"
        )


    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )


    # ========================================================
    # Build everything in a temporary staging directory
    # ========================================================

    with tempfile.TemporaryDirectory(

        prefix=".rule-build-",

        dir=OUTPUT_DIR,

    ) as temp_dir:


        staging_dir = Path(
            temp_dir
        )


        # ----------------------------------------------------
        # Compile in links.txt order
        # ----------------------------------------------------

        for url in links:

            name, fields = (
                results[url]
            )


            write_and_compile(
                name,
                fields,
                staging_dir,
            )


        # ----------------------------------------------------
        # Only publish after every SRS compiled successfully
        # ----------------------------------------------------

        publish(
            staging_dir,
            set(names),
        )


    print(
        f"Successfully generated "
        f"{len(links)} "
        f"rule set(s).",
        flush=True,
    )


if __name__ == "__main__":

    main()
